spring:
  application:
    name: baro_itn
jwt:
  secret:
    key: ${JWT_SECRET_KEY}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
    enabled: true
  packages-to-scan: com.example.baro_itn.domain